apiVersion: apps/v1
kind: Deployment
metadata:
  name: informative-website-deployment
  namespace: smartshopper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: informative-website
  template:
    metadata:
      labels:
        app: informative-website
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: informative-website
          image: 438465130856.dkr.ecr.us-east-1.amazonaws.com/smartshopper/smartshopper-informative-website:0.1.3 # {"$imagepolicy": "smartshopper:informative-website-policy"}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: frontend-url
---
apiVersion: v1
kind: Service
metadata:
  name: informative-website-service
  namespace: smartshopper
spec:
  selector:
    app: informative-website
  ports:
  - port: 80
    targetPort: 80
