apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.8.x
      sourceRef:
        kind: HelmRepository
        name: longhorn
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values