externalIPs:
  enabled: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
    - 10.42.0.0/16
k8sClientRateLimit:
  burst: 200
  qps: 50
k8sServiceHost: 192.168.1.10
k8sServicePort: 6443
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true