    k8sServiceHost: 192.168.1.10
    k8sServicePort: 6443
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
    rollOutCiliumPods: true
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    k8sClientRateLimit:
      qps: 50
      burst: 200
    operator:
      rollOutPods: true
      replicas: 1  
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    ingressController:
      enabled: true
      loadbalancerMode: shared
      service:
        annotations:
          "lbipam.cilium.io/ips": 192.168.1.30



