alertmanager:
  route:
    main:
      enabled: true
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      annotations: {}
      labels: {}
      hostnames:
        - alertmanager.mdch-lab.dev
      parentRefs:
        - name: mdch-lab-gateway
          namespace: cilium
      httpsRedirect: false
      matches:
        - path:
            type: PathPrefix
            value: /
      filters: []
      additionalRules: []

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    forceEnableClusterMode: true
    secrets:
      - slack-webhook-url
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: slack-notifications
      group_by:  ['alertname','namespace']
      group_wait:      30s
      group_interval:  5m
      repeat_interval: 3h

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#alertmanager'
            api_url_file: /etc/alertmanager/secrets/slack-webhook-url
            send_resolved: true
            title: |-
              [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}
            text: |-
              {{ range .Alerts -}}
              *Namespace:* {{ .Labels.namespace }}
              *Summary:* {{ .Annotations.summary }}
              *Description:* {{ .Annotations.description }}
              ---{{ end }}