apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 1h
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 69.8.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-values
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml