k8sServiceHost: 192.168.1.10
k8sServicePort: 6443

k8sClientRateLimit:
  qps: 50
  burst: 200

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.42.0.0/16

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

l2announcements:
  enabled: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true

operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

envoy:
  prometheus:
    serviceMonitor:
      enabled: true

externalIPs:
  enabled: true

rollOutCiliumPods: true
