
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 1h
  releaseName: plex
  chart:
    spec:
      chart: plex-media-server
      version: 1.0.x
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: plex
  valuesFrom:
    - kind: ConfigMap
      name: plex-values