ingress:
  enabled: true
  ingressClassName: "cilium"
  url: "plex.mdch-lab.dev"
  certificateSecret: plex.mdch-lab.dev-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer

pms:
  storageClassName: longhorn

service:
  type: LoadBalancer
  port: 32400
  loadBalancerIP: 192.168.1.21

extraVolumeMounts:
  - name: plex-media
    mountPath: /plex
    readOnly: false

extraVolumes:
  - name: plex-media
    nfs:
      server: 192.168.1.98
      path: /nfs/Plex
      readOnly: false