ingress:
  enabled: false
  url: ""

pms:
  storageClassName: longhorn

service:
  type: LoadBalancer
  port: 32400
  loadBalancerIP: 192.168.1.21

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1


extraEnv:
  ADVERTISE_IP: "http://192.168.1.21:32400,https://plex.mdch-lab.dev:443"
  TZ: "Asia/Jerusalem"
  PLEX_CLAIM: "claim-iJC_bspDrxtB4GaBNx6u"

extraVolumeMounts:
  - name: plex-media
    mountPath: /plex
    readOnly: false

extraVolumes:
  - name: plex-media
    nfs:
      server: 192.168.1.98
      path: /nfs/Plex
      readOnly: false