pms:
  storageClassName: longhorn

service:
  type: LoadBalancer
  port: 32400
  loadBalancerIP: 192.168.1.21

extraEnv:
  ADVERTISE_IP: "192.168.1.21:32400,plex.mdch-lab.dev:443"
  TZ: "Asia/Jerusalem"

extraVolumeMounts:
  - name: plex-media
    mountPath: /plex
    readOnly: false

extraVolumes:
  - name: plex-media
    nfs:
      server: 192.168.1.98
      path: /nfs/Plex
      readOnly: false