apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: smartshopper
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - frontend
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
      - name: ecr-creds
      containers:
      - name: frontend
        image: 438465130856.dkr.ecr.us-east-1.amazonaws.com/smartshopper/smartshopper-frontend:0.1.30 # {"$imagepolicy": "smartshopper:frontend-policy"}
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: auth0-creds
        - secretRef:
            name: backend-url
        - secretRef:
            name: frontend-url
