apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-url
  namespace: monkeytype
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: backend-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: MONKEYTYPE_BACKENDURL
    remoteRef:
      key: /mdch-lab/monkeytype/backend-url