apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db
  namespace: monkeytype
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: DB_NAME
    remoteRef:
      key: /mdch-lab/monkeytype/db/name
  - secretKey: DB_URI
    remoteRef:
      key: /mdch-lab/monkeytype/db/uri
  - secretKey: REDIS_URI
    remoteRef:
      key: /mdch-lab/monkeytype/redis-uri
