apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firebase-env
  namespace: monkeytype
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: firebase-env
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: FIREBASE_APIKEY
    remoteRef:
      key: /mdch-lab/monkeytype/firebase/apikey
  - secretKey: FIREBASE_AUTHDOMAIN
    remoteRef:
      key: /mdch-lab/monkeytype/firebase/authdomain
  - secretKey: FIREBASE_PROJECTID
    remoteRef:
      key: /mdch-lab/monkeytype/firebase/projectid
  - secretKey: FIREBASE_STORAGEBUCKET
    remoteRef:
      key: /mdch-lab/monkeytype/firebase/storagebucket
  - secretKey: FIREBASE_MESSAGINGSENDERID
    remoteRef:
      key: /mdch-lab/monkeytype/firebase/messagingsenderid
  - secretKey: FIREBASE_APPID
    remoteRef:
      key: /mdch-lab/monkeytype/firebase/appid