apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firebase-sa-key
  namespace: monkeytype
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: firebase-sa-key
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: serviceAccountKey.json
    remoteRef:
      key: /mdch-lab/monkeytype/serviceAccountKey.json