apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-url
  namespace: monkeytype
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: frontend-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: FRONTEND_URL
    remoteRef:
      key: /mdch-lab/monkeytype/fronend-url