apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-recaptcha
  namespace: monkeytype
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: google-recaptcha
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: RECAPTCHA_SITE_KEY
    remoteRef:
      key: /mdch-lab/monkeytype/recaptcha/site-key
  - secretKey: RECAPTCHA_SECRET
    remoteRef:
      key: /mdch-lab/monkeytype/recaptcha/sercret