# This file needs to copied to /etc/rancher/k3s/ on the host
disable:
  - "servicelb"
  - "traefik"
  - "metrics-server"
  - "local-storage"

disable-kube-proxy: true

disable-network-policy: true

flannel-backend: "none"

etcd-expose-metrics: true

kube-controller-manager-arg:
  - "bind-address=0.0.0.0"

kube-scheduler-arg:
  - "bind-address=0.0.0.0"