apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared-tunnel
spec:
  selector:
    matchLabels:
      pod: cloudflared
  namespaceSelector:
    matchNames:
      - cloudflare
  podMetricsEndpoints:
    - path: /metrics
      interval: 10s
      scheme: http
      targetPort: 2000
