apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 1h
  releaseName: descheduler
  chart:
    spec:
      chart: descheduler
      version: 0.33.X
      sourceRef:
        kind: HelmRepository
        name: descheduler
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
