# This file needs to copied to /etc/rancher/k3s/ on the host
disable:
  - "kube-proxy"
  - "network-policy"
  - "servicelb"
  - "traefik"
  - "metrics-server"
  - "local-storage"

flannel-backend: "none"

etcd-expose-metrics: true

kube-controller-manager-arg:
  - "bind-address=0.0.0.0"

kube-proxy-arg:
  - "metrics-bind-address=0.0.0.0"

kube-scheduler-arg:
  - "bind-address=0.0.0.0"