# Deploy this manually via kubectl apply -f and restart the Pod
# this is a workaround for the issue that the CoreDNS logs are shown warning messages
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  log.override: |
    #
  stub.server: |
    #