apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - flagger-loadtester.yaml
configMapGenerator:
  - name: flagger-values
    namespace: flagger-system
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: flagger
configurations:
  - kustomizeconfig.yaml