apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger
spec:
  interval: 24h
  url: oci://ghcr.io/fluxcd/charts
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger-loadtester
spec:
  interval: 24h
  url: https://flagger.app