apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: pihole-blue-green
  namespace: pihole
spec:
  provider: kubernetes
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pihole
  progressDeadlineSeconds: 60
  service:
    port: 80
    portDiscovery: true
  analysis:
    interval: 30s
    threshold: 2
    iterations: 5
    metrics:
    - name: dns-error-rate
      templateRef:
        name: dns-error-rate
      thresholdRange:
        max: 1
      interval: 30s
    - name: latency
      templateRef:
        name: latency
      thresholdRange:
        max: 0.5
      interval: 30s
    webhooks:
      - name: smoke-test
        type: pre-rollout
        url: http://flagger-loadtester/
        timeout: 5s
        metadata:
          type: bash
          cmd: "curl -fsS -o /dev/null https://pihole.mdch-lab.dev"
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 5s
        metadata:
          type: cmd
          cmd: "nslookup google.com 192.168.1.20"