apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 1h
  releaseName: k8s-monitoring
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "2.1.x"
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
  valuesFrom:
    - kind: ConfigMap
      name: alloy-values
