cluster:
  name: mdch-lab.dev

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway/loki/api/v1/push


clusterEvents:
  enabled: true
  collector: alloy-logs

nodeLogs:
  enabled: true
  journal:
    units:
      - k3s.service

podLogs:
  enabled: true
  collector: alloy-logs

alloy-logs:
  enabled: true
  # Required when using the Kubernetes API to pod logs
  alloy:
    mounts:
      varlog: true
      dockercontainers: false
    clustering:
      enabled: true
