cluster:
  name: mdch-lab.dev

destinations:
  - name: loki
    type: loki
    url: http://loki-gateway/loki/api/v1/push


clusterEvents:
  enabled: true
  collector: alloy-logs

nodeLogs:
  enabled: true
  journal:
    units:
      - k3s.service

podLogs:
  enabled: true
  collector: alloy-logs
  labelsToKeep: ["app_kubernetes_io_name","container","instance","job","level","namespace","service_name","service_namespace","deployment_environment","deployment_environment_name"]
  structuredMetadata:
    pod: pod  # Set structured metadata "pod" from label "pod"

alloy-logs:
  enabled: true
  # Required when using the Kubernetes API to pod logs
  alloy:
    uiPathPrefix: /pods
    mounts:
      varlog: true
      dockercontainers: false
    clustering:
      enabled: true
