apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - repository.yaml
  - loki-release.yaml
  - k8s-monitoring-release.yaml
configMapGenerator:
  - name: loki-values
    files:
      - values.yaml=loki-values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: k8s-monitoring-values
    files:
      - values.yaml=k8s-monitoring-values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml