deploymentMode: SingleBinary
loki:
  storage:
    bucketNames:
      chunks: loki-local-chunks
      ruler:  loki-local-ruler
      admin:  loki-local-admin
    type: filesystem
  auth_enabled: false
  serviceMonitor:
    enabled: true
    labels:
      app.kubernetes.io/part-of: kube-prometheus-stack
  limits_config:
    volume_enabled: true
  # https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  ruler:
    enable_api: true
test:
  enabled: false
singleBinary:
  replicas: 1
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-datasource
      labels:
        app: loki
        chart: loki
        release: loki
        grafana_datasource: "1"
        app.kubernetes.io/part-of: kube-prometheus-stack
    data:
      loki-datasource.yaml: |-
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki:{{ .Values.loki.server.http_listen_port }}
          version: 1
          isDefault: false
