apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1h
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "6.29.x"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
