apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1h
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "6.16.x"
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
  valuesFrom:
    - kind: ConfigMap
      name: promtail-values
