apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth0-creds
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: auth0-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: AUTH0_DOMAIN
    remoteRef:
      key: /smartshopper/auth0/domain
  - secretKey: REACT_APP_AUTH0_DOMAIN
    remoteRef:
      key: /smartshopper/auth0/domain
  - secretKey: AUTH0_API_AUDIENCE
    remoteRef:
      key: /smartshopper/auth0/api-audience
  - secretKey: REACT_APP_AUTH0_API_AUDIENCE
    remoteRef:
      key: /smartshopper/auth0/api-audience
  - secretKey: AUTH0_AUDIENCE
    remoteRef:
      key: /smartshopper/auth0/api-audience
  - secretKey: REACT_APP_AUTH0_AUDIENCE
    remoteRef:
      key: /smartshopper/auth0/api-audience
  - secretKey: AUTH0_CLIENT_ID
    remoteRef:
      key: /smartshopper/auth0/client-id
  - secretKey: REACT_APP_AUTH0_CLIENT_ID
    remoteRef:
      key: /smartshopper/auth0/client-id
  - secretKey: AUTH0_CALLBACK_URL
    remoteRef:
      key: /smartshopper/auth0/callback-url
  - secretKey: REACT_APP_AUTH0_CALLBACK_URL
    remoteRef:
      key: /smartshopper/auth0/callback-url
  - secretKey: AUTH0_REDIRECT_URI
    remoteRef:
      key: /smartshopper/auth0/redirect-uri
  - secretKey: REACT_APP_AUTH0_REDIRECT_URI
    remoteRef:
      key: /smartshopper/auth0/redirect-uri
  - secretKey: AUTH0_CLIENT_SECRET
    remoteRef:
      key: /smartshopper/auth0/client-secret
