apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-creds
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: aws-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: /smartshopper/aws/access-key
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: /smartshopper/aws/secret-access-key
  - secretKey: AWS_REGION
    remoteRef:
      key: /smartshopper/aws/region
  - secretKey: S3_BUCKET_NAME
    remoteRef:
      key: /smartshopper/aws/bucket-name