apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-firebase-creds
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: backend-firebase-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: FIREBASE_SERVICE_ACCOUNT_BASE64
    remoteRef:
      key: /smartshopper/firebase/service-account-base64