apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-url
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: backend-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: API_URL
    remoteRef:
      key: /smartshopper/backend-url
  - secretKey: REACT_APP_API_URL
    remoteRef:
      key: /smartshopper/frontend/api-url
