apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-url
  namespace: smartshopper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: backend-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: API_URL
    remoteRef:
      key: /smartshopper/backend-url