apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: db-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: MYSQL_HOST
    remoteRef:
      key: /smartshopper/db/host
  - secretKey: MYSQL_PORT
    remoteRef:
      key: /smartshopper/db/port
  - secretKey: MYSQL_DATABASE
    remoteRef:
      key: /smartshopper/db/name
  - secretKey: MYSQL_USER
    remoteRef:
      key: /smartshopper/db/user
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: /smartshopper/db/password
  - secretKey: MYSQL_ROOT_PASSWORD
    remoteRef:
      key: /smartshopper/db/root-password