apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend-url
  namespace: smartshopper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: frontend-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: REACT_APP_FRONTEND_URL
    remoteRef:
      key: /smartshopper/frontend-url
