apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-creds
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: google-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: GOOGLE_CLIENT_ID
    remoteRef:
      key: /smartshopper/google/client-id
  - secretKey: GOOGLE_CLIENT_SECRET
    remoteRef:
      key: /smartshopper/google/client-secret