apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-key
  namespace: smartshopper
  annotations:
    flagger.app/config-tracking: "disabled"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: openai-key
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: /smartshopper/openai/api-key