apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: smartshopper-secretstore
  namespace: smartshopper
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: smartshopper-awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: smartshopper-awssm-secret
            key: secret-access-key