apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway
spec:
  interval: 1h
  releaseName: envoy-gateway
  chartRef:
    kind: OCIRepository
    name: envoy-gateway