apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml
  - httproute.yaml

configMapGenerator:
  - name: qbittorrent-values
    namespace: qbittorrent
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml