
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 1h
  releaseName: qbittorrent
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: qbittorrent
      version: 0.4.x
      sourceRef:
        kind: HelmRepository
        name: gabe565
  valuesFrom:
    - kind: ConfigMap
      name: qbittorrent-values