
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  releaseName: qbittorrent
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: qbittorrent
      version: 5.1.x
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
      verify: # verify the chart signature with Cosign keyless
        provider: cosign 
  valuesFrom:
    - kind: ConfigMap
      name: qbittorrent-values