apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - monitoring-helm-release.yaml
  - monitoring-ns.yaml

configMapGenerator:
  - name: monitoring-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml