apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1h
  releaseName: argocd
  chart:
    spec:
      chart: argo-cd
      version: 8.0.x
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argocd
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: argocd-values