apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: pihole-gateway
  namespace: pihole
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: pihole-gateway
  listeners:
  - name: dns-tcp
    protocol: TCP
    port: 53
  - name: dns-udp
    protocol: UDP
    port: 53
  - name: web
    hostname: pihole.mdch-lab.dev
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: pihole.mdch-lab.dev-cert
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: pihole-gateway
  namespace: pihole
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                lbipam.cilium.io/ips: "192.168.1.25"
            spec:
              allocateLoadBalancerNodePorts: false
