apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: pihole-dns-gateway
  namespace: pihole
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: pihole-dns-gateway
  addresses:
  - type: IPAddress
    value: 192.168.1.25
  listeners:
  - name: dns-tcp
    protocol: TCP
    port: 53
  - name: dns-udp
    protocol: UDP
    port: 53
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: pihole-dns-gateway
  namespace: pihole
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                lbipam.cilium.io/ips: "192.168.1.25"
            spec:
              loadBalancerClass: "io.cilium/l2-announcer"
              allocateLoadBalancerNodePorts: false
