apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: pihole-gateway
  namespace: envoy-gateway
spec:
  gatewayClassName: envoy-gateway
  listeners:
  - name: dns-tcp
    protocol: TCP
    port: 53
    allowedRoutes:
      namespaces:
        from: Same
  - name: dns-udp
    protocol: UDP
    port: 53
    allowedRoutes:
      namespaces:
        from: Same
