apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml
  - pihole-secret.yaml
  - httproute.yaml
  - pihole-policy.yaml
configMapGenerator:
  - name: pihole-values
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: pihole
  - name: pihole-grafana-dashboards
    files:
      - dashboards/10176_rev3.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: pihole
        kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml