apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml
  - pihole-secret.yaml
  - httproute.yaml
  - pihole-policy.yaml
  - flagger/blue-green.yaml
  - flagger/metrics.yaml

configMapGenerator:
  - name: pihole-values
    namespace: pihole
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml