apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - release.yaml
  - repository.yaml
  - pihole-ns.yaml
  - pihole-secret.yaml
  - gateway.yaml

configMapGenerator:
  - name: pihole-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml