apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: pihole-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: password
    remoteRef:
      key: /mdch-lab/pihole/password