
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      version: 2.29.x
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
  valuesFrom:
    - kind: ConfigMap
      name: pihole-values