apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: pihole-dns-tcp
  namespace: pihole
spec:
  parentRefs:
  - name: pihole-gateway
    sectionName: dns-tcp
  rules:
  - backendRefs:
    - name: pihole-dns
      port: 53
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: pihole-dns-udp
  namespace: pihole
spec:
  parentRefs:
  - name: pihole-gateway
    sectionName: dns-udp
  rules:
  - backendRefs:
    - name: pihole-dns
      port: 53
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pihole-web
  namespace: pihole
spec:
  parentRefs:
  - name: pihole-gateway
    sectionName: web
  hostnames:
  - "pihole.mdch-lab.dev"
  rules:
  - matches:
    - path:
        type: Exact
        value: "/"
    filters:
    - type: RequestRedirect
      requestRedirect:
        path:
          type: ReplaceFullPath
          replaceFullPath: /login
        statusCode: 302 
  - backendRefs:
    - name: pihole-web
      port: 80
