# TCP 53
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: pihole-dns-tcp
  namespace: pihole
spec:
  parentRefs:
  - name: pihole-gateway
    namespace: envoy-gateway
    sectionName: dns-tcp
  rules:
  - backendRefs:
    - name: pihole
      port: 53
---
# UDP 53
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: pihole-dns-udp
  namespace: pihole
spec:
  parentRefs:
  - name: pihole-gateway
    namespace: envoy-gateway
    sectionName: dns-udp
  rules:
  - backendRefs:
    - name: pihole
      port: 53
