apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
spec:
  interval: 1h
  wait: true
  prune: true
  timeout: 5m
  path: ./infrastructure/controllers/cilium
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  dependsOn:
    - name: gateway-api-crds
