apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 1h
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: 1.17.x
      sourceRef:
        kind: HelmRepository
        name: cilium
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values