k8sServiceHost: 192.168.1.10
k8sServicePort: 6443

k8sClientRateLimit:
  qps: 50
  burst: 200

l2announcements:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    loadBalancerIP: 192.168.1.30
    allocateLoadBalancerNodePorts: false

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.42.0.0/16

kubeProxyReplacement: "true"
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

loadBalancer:
  l7:
    backend: envoy

hubble:
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
      className: cilium
      hosts:
        - hubble.mdch-lab.dev
      tls:
        - secretName: hubble.mdch-lab.dev
          hosts:
            - hubble.mdch-lab.dev
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  rollOutPods: true
  replicas: 1
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

envoy:
  rollOutPods: true
  prometheus:
    serviceMonitor:
      enabled: true

externalIPs:
  enabled: true

rollOutCiliumPods: true
