# podinfo-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: test
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flagger-examples
  path: ./kustomize/podinfo
  prune: true
