apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: podinfo-gateway
  namespace: test
spec:
  gatewayClassName: cilium
  addresses:
  - type: IPAddress
    value: 192.168.1.27
  listeners:
  - name: web
    hostname: podinfo.mdch-lab.dev
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: wildcard-mdch-lab-dev-cert
        namespace: cert-manager