apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - longhorn-helm-release.yaml
  - longhorn-ns.yaml

configMapGenerator:
  - name: longhorn-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml