apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mdch-lab-dev
  namespace: cert-manager
spec:
  secretName: wildcard-mdch-lab-dev-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  commonName: '*.mdch-lab.dev'
  dnsNames:
    - '*.mdch-lab.dev'
    - mdch-lab.dev
  privateKey:
    algorithm: RSA
    size: 2048
