apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - cert-manager-helm-release.yaml
  - cert-manager-ns.yaml
  - letsencrypt-cluster-issuer.yaml

configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml