apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monkeytype
resources:
  - backend-deployment.yaml
  - backend-httproute.yaml
configMapGenerator:
  - name: backend-configuration
    files:
      - backend-configuration.json
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monkeytype
configurations:
  - kustomizeconfig.yaml