apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: informative-website-blue-green
  namespace: smartshopper
spec:
  provider: gatewayapi:v1
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: informative-website-deployment
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # service port number
    port: 80
    # Gateway API HTTPRoute host names
    hosts:
     - smartshopper.mdch-lab.dev
    # Reference to the Gateway that the generated HTTPRoute would attach to.
    gatewayRefs:
      - name: smartshopper-gateway
        namespace: smartshopper
  analysis:
    # schedule interval (default 60s)
    interval: 40s
    # max number of failed checks before rollback
    threshold: 1
    # number of checks to run before rollback
    iterations: 3
    # testing (optional)
    webhooks:
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 5s
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 -host smartshopper.mdch-lab.dev https://smartshopper-gateway/"