apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repositories.yaml
  - deployment-crds.yaml
  - deployment-crs.yaml
  - release.yaml
configMapGenerator:
  - name: external-secrets-values
    namespace: external-secrets
    files:
      - values.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: external-secrets
configurations:
  - kustomizeconfig.yaml