apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.17.x
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values 