apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-token
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: slack-webhook-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: SLACK_WEBHOOK_URL
    remoteRef:
      key: /mdch-lab/alertmanager/slack-webhook-url