apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webhook-token
  namespace: smartshopper
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: smartshopper-secretstore
    kind: SecretStore
  target:
    name: webhook-token
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: token
    remoteRef:
      key: /smartshopper/webhook-token