apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook-url
  namespace: flagger-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: slack-webhook-url
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: url
    remoteRef:
      key: /mdch-lab/flagger/slack/webhook-url